### ISSUE TITLE
Enchantment Error

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#135]
```
 [08:16:11] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to EnchantmentAPI v4.27
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1001) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1063) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1355) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:400) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:123) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:119) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.phantomapi.construct.ControllablePlugin.scheduleSyncRepeatingTask(ControllablePlugin.java:520) ~[?:?]
	at org.phantomapi.sync.Task.<init>(Task.java:32) ~[?:?]
	at org.phantomapi.sync.Task.<init>(Task.java:43) ~[?:?]
	at org.cyberpwn.effex.effect.VampiricEffect$1.<init>(VampiricEffect.java:23) ~[?:?]
	at org.cyberpwn.effex.effect.VampiricEffect.play(VampiricEffect.java:23) ~[?:?]
	at org.cyberpwn.effex.enchantments.SoulEruptionEnchantment.applyEffect(SoulEruptionEnchantment.java:55) ~[?:?]
	at com.rit.sucy.enchanting.EListener.onHit(EListener.java:105) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor605.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	... 24 more
```

**Comment by cyberpwnn** [comment]
It looks like Effex did not load up properly

Try using this command

```/phast unload Effex; load Effex; thrash; ```

**Comment by cyberpwnn** [comment]
This is actually a phantom issue.

Shadow 2 fixes this issue completley https://github.com/PhantomAPI/Phantom/releases
