### ISSUE TITLE
EnchantmentAPI Error

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#137]
```
[23:16:03] [Server thread/WARN]: [EnchantmentAPI] Task #6013640 for EnchantmentAPI v4.27 generated an exception
java.lang.NullPointerException
	at com.rit.sucy.Anvil.v1_8_6.MainAnvil$2.run(MainAnvil.java:121) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by cyberpwnn** [comment]
Anvils are disabled. That may be helping cause that.
