### ISSUE TITLE
EnchantmentAPI Error #2

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#138]
```
[23:10:13] [Server thread/ERROR]: Could not pass event EntityDamageEvent to EnchantmentAPI v4.27
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:539) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1112) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:860) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:748) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityLiving.K(EntityLiving.java:211) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.Entity.t_(Entity.java:263) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1457) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityHuman.t_(EntityHuman.java:174) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:293) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:385) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:8) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at org.cyberpwn.effex.enchantments.DemolitionEnchantment.applyDefenseEffect(DemolitionEnchantment.java:33) ~[?:?]
	at com.rit.sucy.enchanting.EListener.onDamaged(EListener.java:129) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	... 30 more
```

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/a3bfc7c4ece421032096d4cee54c06620df07a53
