### ISSUE TITLE
CurrencyShops Error

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#205]
```
[21:51:10] [Server thread/WARN]: java.lang.NullPointerException
[21:51:10] [Server thread/WARN]: 	at org.cyberpwn.currecnyshops.object.GShop.trySellAll(GShop.java:242)
[21:51:10] [Server thread/WARN]: 	at org.cyberpwn.currencyshops.ShopCommandController.onCommand(ShopCommandController.java:164)
[21:51:10] [Server thread/WARN]: 	at org.phantomapi.command.CommandBus.<init>(CommandBus.java:137)
[21:51:10] [Server thread/WARN]: 	at org.phantomapi.core.CommandRegistryController.processCommand(CommandRegistryController.java:177)
[21:51:10] [Server thread/WARN]: 	at org.phantomapi.core.CommandRegistryController.on(CommandRegistryController.java:156)
[21:51:10] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor449.invoke(Unknown Source)
[21:51:10] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:51:10] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[21:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[21:51:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[21:51:10] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:51:10] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[21:51:10] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[21:51:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cyberpwnn** [comment]
Need reproduction Steps

**Comment by SwiftSwamp** [comment]
It's just spamming console, I have no clue how to force the error.
Using latest everything at the moment.

**Comment by cyberpwnn** [comment]
try ```/phast reload CurrencyShops;```
