### ISSUE TITLE
Nest Api Nullpointer

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#255]
```
Caused by: java.lang.NullPointerException
	at org.phantomapi.nest.Nest.getBlock(Nest.java:34)
	at org.cyberpwn.factionsplus.FactionScanner$7.run(FactionScanner.java:678)
	at org.cyberpwn.factionsplus.FactionScanner$7.run(FactionScanner.java:1)
	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
	at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:373)
	at com.boydti.fawe.util.TaskManager$4.run(TaskManager.java:369)
	at com.boydti.fawe.object.RunnableVal.run(RunnableVal.java:14)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
	... 1 more
```

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/FactionsPlus/commit/2998c8582470aa041a3ddd368c4022c509afc29a
