### ISSUE TITLE
ASkyblock Handler Null Pointer

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#257]
```
java.lang.NullPointerException
  at org.cyberpwn.commune.ASkyblockBlockHandler.canModify(ASkyblockBlockHandler.java:25)
  at org.phantomapi.core.BlockCheckController.canModify(BlockCheckController.java:66)
  at org.phantomapi.world.Blocks.getModify(Blocks.java:65)
  at org.phantomapi.world.Blocks.canModify(Blocks.java:41)
  at org.cyberpwn.effex.EffexController.on(EffexController.java:1252)
  at sun.reflect.GeneratedMethodAccessor514.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
  at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286)
  at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:215)
  at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:637)
  at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
  at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
  at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
  at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
  at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
  at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
  at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/5628a604216aa4f3f614e2c195a1cd99c1424e85
