### ISSUE TITLE
Effex Null Pointer

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#272]
```
[08:20:05] [Server thread/WARN]: [Effex] Task #1765 for Effex v3 generated an exception
java.lang.NullPointerException
	at org.cyberpwn.effex.EffexController.onTick(EffexController.java:663) ~[?:?]
	at org.phantomapi.construct.Controller.tick(Controller.java:153) ~[?:?]
	at org.phantomapi.construct.ControllablePlugin$4$1.run(ControllablePlugin.java:286) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by SwiftSwamp** [comment]
All Enchantments are not usable since 3.0.

**Comment by SwiftSwamp** [comment]
Never mind, something else was causing it.. rebooted and it's fixed. Maybe thrashing?

**Comment by GetDerpy** [comment]
Moss works for me, but not players
I can drop snare on a bow, but other players can't
Spring isn't working
Essence breaks after 10/15 minutes of the server being up

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Effex/commit/0d6e1ef076eac0955533ef5479a8ed79cb38cbd0
