### ISSUE TITLE
Phantom GZIP Error

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#313]
Happened on Startup

```
[11:05:01] [Craft Scheduler Thread - 26/WARN]: java.io.EOFException
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at org.phantomapi.filesystem.Serializer.deserialize(Serializer.java:57)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at org.phantomapi.filesystem.Serializer.deserializeFromFile(Serializer.java:95)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at org.phantomapi.core.NestController$2$1.async(NestController.java:187)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at org.phantomapi.async.A$1.run(A.java:34)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:05:01] [Craft Scheduler Thread - 26/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cyberpwnn** [comment]
This can happen sometimes.
