### ISSUE TITLE
Technic Error

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#333]
```
[17:49:20] [Server thread/WARN]: [Phantom] Task #10734164 for Phantom vE2 generated an exception
java.lang.NoSuchMethodError: org.phantomapi.lang.GSound.<init>(Lorg/bukkit/Sound;FF)V
	at org.cyberpwn.technic.block.VaccumHopperBlock$1.run(VaccumHopperBlock.java:135) ~[?:?]
	at org.phantomapi.sync.ExecutiveRunnable.run(ExecutiveRunnable.java:28) ~[?:?]
	at org.phantomapi.lang.GList$1.onIterate(GList.java:129) ~[?:?]
	at org.phantomapi.sync.ExecutiveIterator.next(ExecutiveIterator.java:79) ~[?:?]
	at org.phantomapi.sync.ExecutivePool$1.run(ExecutivePool.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/90a4f43d3e3e8ef51800f72416798d99208e53a0
