### ISSUE TITLE
Technic 2.6 Print Exception (Not error)

### ISSUE THREAD

**Issue by cyberpwnn** [cyberpwnn/GlacialRealms#357]
```
java.lang.IllegalStateException: Asynchronous entity world add!
[18:41:14 WARN]:        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[18:41:14 WARN]:        at net.minecraft.server.v1_8_R3.World.b(World.java:2633)
[18:41:14 WARN]:        at net.minecraft.server.v1_8_R3.Chunk.addEntities(Chunk.java:820)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[18:41:14 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
[18:41:14 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:126)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:568)
[18:41:14 WARN]:        at org.bukkit.Location.getBlock(Location.java:87)
[18:41:14 WARN]:        at org.cyberpwn.technic.multiblock.SmelteryMultiblock.getOutputInventories(SmelteryMultiblock.java:437)
[18:41:14 WARN]:        at org.cyberpwn.technic.multiblock.SmelteryMultiblock.hasOutputSpace(SmelteryMultiblock.java:274)
[18:41:14 WARN]:        at org.cyberpwn.technic.multiblock.SmelteryMultiblock.tryCycle(SmelteryMultiblock.java:127)
[18:41:14 WARN]:        at org.cyberpwn.technic.multiblock.SmelteryMultiblock$2.async(SmelteryMultiblock.java:108)
[18:41:14 WARN]:        at org.phantomapi.async.A$1.run(A.java:34)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[18:41:14 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[18:41:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[18:41:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
```

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Technic/commit/14dbc80b795de2765b1bfd05423d0df653269c47
