### ISSUE TITLE
Technic NullPointer

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#416]
```
[13:09:06] [Server thread/WARN]: [Technic] Task #1622 for Technic v2.9 generated an exception
java.lang.NullPointerException
	at org.phantomapi.nest.Nest.getBlock(Nest.java:77) ~[?:?]
	at org.cyberpwn.technic.block.SpawnerBlock.onTick(SpawnerBlock.java:133) ~[?:?]
	at org.phantomapi.construct.Controller.tick(Controller.java:163) ~[?:?]
	at org.phantomapi.construct.ControllablePlugin$4$1.run(ControllablePlugin.java:292) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by SwiftSwamp** [comment]
This was fixed in 3.0 along with some other bugs. Closing.
