### ISSUE TITLE
CurrencyShops Error

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#432]
```
[19:39:41] [Server thread/WARN]: java.lang.NullPointerException
[19:39:41] [Server thread/WARN]: 	at org.cyberpwn.currecnyshops.object.GShop.trySellAll(GShop.java:243)
[19:39:41] [Server thread/WARN]: 	at org.cyberpwn.currencyshops.ShopCommandController.onCommand(ShopCommandController.java:173)
[19:39:41] [Server thread/WARN]: 	at org.phantomapi.command.CommandBus.<init>(CommandBus.java:137)
[19:39:41] [Server thread/WARN]: 	at org.phantomapi.core.CommandRegistryController.processCommand(CommandRegistryController.java:196)
[19:39:41] [Server thread/WARN]: 	at org.phantomapi.core.CommandRegistryController.on(CommandRegistryController.java:175)
[19:39:41] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor543.invoke(Unknown Source)
[19:39:41] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:39:41] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:39:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[19:39:41] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[19:39:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[19:39:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[19:39:41] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[19:39:41] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[19:39:41] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[19:39:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cyberpwnn** [comment]
It's being printed. Ill remove the log event

**Comment by Puretie** [comment]
Adding stale label due to lack of further progress following the three day rule.

**Comment by cyberpwnn** [comment]
This is not an error

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/CurrencyShops/commit/48519d994e488ab2b2871001f8fa428cf78f2b48
