### ISSUE TITLE
Commune SpawnerSpawnEvent

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#480]
```
[22:38:18] [Server thread/ERROR]: Could not pass event SpawnerSpawnEvent to Commune v8.8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callSpawnerSpawnEvent(CraftEventFactory.java:144) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MobSpawnerAbstract.a(MobSpawnerAbstract.java:197) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MobSpawnerAbstract.c(MobSpawnerAbstract.java:109) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.TileEntityMobSpawner.c(SourceFile:55) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
```

**Comment by cyberpwnn** [comment]
Reopen when you have the full exception

**Comment by cyberpwnn** [comment]
Bad exception

**Comment by cyberpwnn** [comment]
Um

``` java
@EventHandler
public void on(CreatureSpawnEvent e)
{
	if(e.getEntityType().equals(EntityType.WITHER))
	{
		if(!e.getLocation().getWorld().getName().equals(witherworld) && !allowWitherSpawns)
		{
			Area a = new Area(e.getLocation(), 6);
			
			for(Player i : a.getNearbyPlayers())
			{
				i.sendMessage(F.color("&8&l(&4&l!&8&l) &4Withers can only be spawned in " + witherworld));
			}
			
			e.setCancelled(true);
		}
	}
}
```

**Comment by cyberpwnn** [comment]
I tried throwing a t/c on it, but I cant reproduce it so I have no idea if that would remove the spam the only other thing I could think is POWERTOOL

**Comment by cyberpwnn** [comment]
I could try entity spawn event since some jars do not contain CreatureType.class (or are indirectly referenced like nms code) but im not sure if it actually would prevent withers.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/b954655b1213aa12ce170f42cb9a9c9403a598f2
