### ISSUE TITLE
Vacuum Hoppers - Boo PaperSpigot

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#492]
```
[05:20:53] [Craft Scheduler Thread - 88/WARN]: java.lang.Throwable
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:459)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:114)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:144)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:603)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.Location.getChunk(Location.java:78)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.phantomapi.world.Area.getNearbyEntities(Area.java:140)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.cyberpwn.technic.block.VaccumHopperBlock$1.async(VaccumHopperBlock.java:119)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.phantomapi.async.A$1.run(A.java:29)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[05:20:53] [Craft Scheduler Thread - 88/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[05:20:53] [Craft Scheduler Thread - 88/ERROR]: stopTiming called async for ASkyBlock - chunkLoad - Entities
```

**Comment by cyberpwnn** [comment]
The problem is being caused by ```at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)```. The fact that vacuum hoppers are showing up is because it is being ticked.

**Comment by SwiftSwamp** [comment]
Couldn't you surpass the warning? It makes it extremely hard to view live console output or go through logs for actual errors.

**Comment by cyberpwnn** [comment]
No, i cannot suppress an error from happening because its happening inside of paperspigot. Im just showing up in the timings stack trace.

**Comment by SwiftSwamp** [comment]
That's upsetting, gg watching console live or easily going through them :/
