### ISSUE TITLE
Skyblock Crash Because of Hoppers

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#551]
Has been happening for a while, need to figure out what's actually causing it. 

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 11/22/16 12:20 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:501)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:420)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:228)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:212)
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1533)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:603)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:848)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:376)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:501)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.a(TileEntityHopper.java:420)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:228)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:212)

-- Block entity being ticked --
Details:
	Name: Hopper // net.minecraft.server.v1_8_R3.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.server.v1_8_R3.BlockHopper)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-3918,118,-9596), Chunk: (at 2,7,4 in -245,-600; contains blocks -3920,0,-9600 to -3905,255,-9585), Region: (-8,-19; contains chunks -256,-608 to -225,-577, blocks -4096,0,-9728 to -3585,255,-9217)
	Actual block type: ID #0 (tile.air // net.minecraft.server.v1_8_R3.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1533)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:603)

-- Affected level --
Details:
	Level name: ASkyBlock
	All players: 32 total; [EntityPlayer['KFCDriveThrough'/1715091, l='ASkyBlock', x=304.41, y=193.50, z=5987.78](KFCDriveThrough at 304.40846522361363,193.5,5987.776587975505), EntityPlayer['Magstar1670'/1730081, l='ASkyBlock', x=2453.70, y=111.00, z=8929.39](Magstar1670 at 2453.699999988079,111.0,8929.388753865076), EntityPlayer['xxxThe_Beast'/8043056, l='ASkyBlock', x=-5330.42, y=143.00, z=56.30](xxxThe_Beast at -5330.4152548377115,143.0,56.30000001192093), EntityPlayer['mkll47'/12451444, l='ASkyBlock', x=-6319.46, y=131.00, z=9281.38](mkll47 at -6319.464041224274,131.0,9281.381098921525), EntityPlayer['Fraantiq'/14296119, l='ASkyBlock', x=-2377.14, y=126.00, z=8099.86](Fraantiq at -2377.137499988079,126.0,8099.862500011921), EntityPlayer['K0T'/15405865, l='ASkyBlock', x=2419.59, y=120.00, z=6052.66](K0T at 2419.593948474132,120.0,6052.6550937264055), EntityPlayer['SilentxKiller51'/15892203, l='ASkyBlock', x=-5387.27, y=2.00, z=8660.77](SilentxKiller51 at -5387.26796553655,2.0,8660.770497170883), EntityPlayer['ldog20'/15285304, l='ASkyBlock', x=-5394.46, y=49.20, z=-2449.49](ldog20 at -5394.461321994797,49.200000047683716,-2449.48797661553), EntityPlayer['ThePandaWolf'/19106284, l='ASkyBlock', x=-5348.71, y=122.40, z=-49.22](ThePandaWolf at -5348.711994555916,122.39606460756045,-49.21753004358739), EntityPlayer['TheSenpaiWolf'/19346250, l='ASkyBlock', x=-5331.30, y=53.20, z=33.70](TheSenpaiWolf at -5331.300000011921,53.200000047683716,33.69999998807907), EntityPlayer['Fadorico'/20699795, l='ASkyBlock', x=2465.70, y=110.00, z=9059.47](Fadorico at 2465.7013257143244,110.0,9059.467069105918), EntityPlayer['ReaverRage'/20859670, l='ASkyBlock', x=-2370.70, y=121.00, z=8700.42](ReaverRage at -2370.699999988079,121.0,8700.421731975428), EntityPlayer['JustBlazzed'/20641445, l='ASkyBlock', x=5996.70, y=220.00, z=4175.95](JustBlazzed at 5996.699999988079,220.0,4175.951902256891), EntityPlayer['BufffySummers'/21033836, l='ASkyBlock', x=2393.98, y=162.09, z=9004.71](BufffySummers at 2393.9776031184356,162.09127524109326,9004.706901653311), EntityPlayer['EeveePvP'/21698928, l='ASkyBlock', x=-2378.25, y=159.00, z=8709.39](EeveePvP at -2378.252951498909,159.0,8709.389963472586), EntityPlayer['MK0119'/22685603, l='ASkyBlock', x=-5336.97, y=32.00, z=-11.92](MK0119 at -5336.965734282135,32.0,-11.919197053935319), EntityPlayer['WolfiezRawr'/22803990, l='ASkyBlock', x=-8639.20, y=119.60, z=8172.22](WolfiezRawr at -8639.198631862313,119.60202918334608,8172.222308111345), EntityPlayer['artemis_2002'/22813023, l='ASkyBlock', x=-8999.57, y=134.00, z=8109.50](artemis_2002 at -8999.570307689328,134.0,8109.503014435956), EntityPlayer['Puggonator'/23110654, l='ASkyBlock', x=-3916.52, y=117.00, z=-9595.35](Puggonator at -3916.51674743118,117.0,-9595.345842153874), EntityPlayer['Hamm3rTimes18'/23178269, l='ASkyBlock', x=-5430.53, y=22.00, z=4141.51](Hamm3rTimes18 at -5430.5345482367175,22.0,4141.514263626202), EntityPlayer['DRxNEMOxAVITAN'/23183766, l='ASkyBlock', x=-5437.57, y=13.00, z=4137.73](DRxNEMOxAVITAN at -5437.566739083961,13.0,4137.728191194285), EntityPlayer['shajj'/23211251, l='ASkyBlock', x=-4500.57, y=98.02, z=5959.74](shajj at -4500.567608598274,98.01772813370563,5959.742959685929), EntityPlayer['Uniqueness'/23333554, l='ASkyBlock', x=-5338.07, y=37.00, z=2079.32](Uniqueness at -5338.071949648416,37.0,2079.315295735732), EntityPlayer['Cosmic_Fyre'/23512196, l='ASkyBlock', x=-5353.36, y=32.16, z=-9.59](Cosmic_Fyre at -5353.3629381381415,32.158146761236615,-9.593500959787162), EntityPlayer['DoctorDanke'/24157280, l='ASkyBlock', x=-8626.30, y=52.63, z=8173.70](DoctorDanke at -8626.300000011921,52.625526064017,8173.699999988079), EntityPlayer['Poke_King'/24519543, l='ASkyBlock', x=-5470.89, y=144.00, z=71.88](Poke_King at -5470.886642486357,144.0,71.88406565176915), EntityPlayer['Leah604'/24725964, l='ASkyBlock', x=-6288.23, y=135.00, z=9907.71](Leah604 at -6288.234302307469,135.0,9907.714933812274), EntityPlayer['Delraman'/24741219, l='ASkyBlock', x=2390.43, y=178.00, z=8995.70](Delraman at 2390.429789778873,178.0,8995.699999988079), EntityPlayer['lapis_block'/24891477, l='ASkyBlock', x=-5346.70, y=40.00, z=2057.43](lapis_block at -5346.699999988079,40.0,2057.426712215076), EntityPlayer['SylkyPvP'/24903175, l='ASkyBlock', x=-1799.49, y=127.00, z=-6899.51](SylkyPvP at -1799.4893804980575,127.0,-6899.5090867172985), EntityPlayer['Xaxios'/24903403, l='ASkyBlock', x=8049.94, y=117.00, z=-4514.23](Xaxios at 8049.939064342991,117.0,-4514.225254180578), EntityPlayer['NeoFlex'/24919891, l='ASkyBlock', x=2390.55, y=178.00, z=9006.30](NeoFlex at 2390.5519653667984,178.0,9006.300000011921)]
	Chunk stats: ServerChunkCache: 2091 Drop: 0
	Level seed: 7017433371698618164
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 80473054 game time, 80473054 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 68015 (now: false), thunder time: 27184 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:848)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:376)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by SwiftSwamp** [comment]
The block coordinates of the crash is different every time.

**Comment by SwiftSwamp** [comment]
Apparently it was fixed with FAWE... but doesnt' seem like that's our case unless it's something else: https://github.com/boy0001/FastAsyncWorldedit/issues/151

**Comment by cyberpwnn** [comment]
Ive seen that issue, its not the same thing. Its when you for example do //set hopper

**Comment by cyberpwnn** [comment]
We're sitting ducks no need to overbloat the high priority tags

**Comment by SwiftSwamp** [comment]
Resolved, seems that it was something interacting with Monster Spawners causing the issue from one of the following plugins: SilkSpawners, EssentialsX (Currently reverted to Spigot Essentials) and or mcMMO. These plugins were taken into consideration after cybers information regarding the fact that even though entity crud isn't hoppers, it could still impact them and sure enough, that was the case.
