### ISSUE TITLE
Icing Bug

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#589]
```
[11:00:29] [Server thread/WARN]: java.lang.NoSuchFieldException: playerConnection
[11:00:29] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[11:00:29] [Server thread/WARN]: 	at org.phantomapi.nms.NMSX.showPickup(NMSX.java:1023)
[11:00:29] [Server thread/WARN]: 	at org.cyberpwn.icing.abilities.StealthSnatching.onTick(StealthSnatching.java:80)
[11:00:29] [Server thread/WARN]: 	at org.phantomapi.construct.Controller.tick(Controller.java:170)
[11:00:29] [Server thread/WARN]: 	at org.phantomapi.construct.ControllablePlugin$4$1.run(ControllablePlugin.java:298)
[11:00:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[11:00:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[11:00:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[11:00:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[11:00:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[11:00:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[11:00:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cyberpwnn** [comment]
What did you do....

**Comment by cyberpwnn** [comment]
Oh, im going to guess it has to do with wraiths. Someone use /pha t wraith? Patching...

**Comment by cyberpwnn** [comment]
K6 Fixes this
