### ISSUE TITLE
FAWE Login Error

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#600]
Not sure if it's directly tied with Commune but this error goes off every login (On the reset server, same settings that you gave me regarding FAWE):

```
[16:35:03] [Craft Scheduler Thread - 76/WARN]: Exception in thread "Craft Scheduler Thread - 76" 
[16:35:03] [Craft Scheduler Thread - 76/WARN]: org.apache.commons.lang.UnhandledException: Plugin FastAsyncWorldEdit v16.11.17-e16bcae-372-9.11.4 generated an exception while executing task 1547
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.cyberpwn.commune.ChangelogController$3.async(ChangelogController.java:237)
	at org.phantomapi.async.A$1.run(A.java:29)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/f4d2f96e092341cfde41ec15d905af8ec2f64798
