### ISSUE TITLE
Commune Won't Enable

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#607]
I'm using the versions listed in the required plugins / versions.

```
[02:11:01] [Server thread/INFO]: [Commune] Enabling Commune v9.6
[02:11:01] [Server thread/ERROR]: Error occurred while enabling Commune v9.6 (Is it up to date?)
java.lang.NullPointerException
	at de.dustplanet.util.SilkUtil.getWorldGuard(SilkUtil.java:939) ~[?:?]
	at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:116) ~[?:?]
	at de.dustplanet.util.SilkUtil.hookIntoSilkSpanwers(SilkUtil.java:130) ~[?:?]
	at org.cyberpwn.commune.CombatController.<init>(CombatController.java:61) ~[?:?]
	at org.cyberpwn.commune.CommuneController.<init>(CommuneController.java:208) ~[?:?]
	at org.cyberpwn.commune.Commune.enable(Commune.java:33) ~[?:?]
	at org.phantomapi.construct.ControllablePlugin.onEnable(ControllablePlugin.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[02:11:01] [Server thread/INFO]: [Commune] Disabling Commune v9.6
[02:11:01] [Server thread/ERROR]: Error occurred while disabling Commune v9.6 (Is it up to date?)
java.lang.NullPointerException
	at org.cyberpwn.commune.Commune.disable(Commune.java:53) ~[?:?]
	at org.phantomapi.construct.ControllablePlugin.onDisable(ControllablePlugin.java:253) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paperspigot-1.8.8.jar:git-PaperSpigot-8b18730]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by SwiftSwamp** [comment]
Provides this error when enabling it on normal spigot: 

```
[02:12:10] [Server thread/ERROR]: Error occurred while enabling Commune v9.6 (Is it up to date?)
java.lang.NoClassDefFoundError: de/dustplanet/util/SilkUtil
	at org.cyberpwn.commune.CombatController.<init>(CombatController.java:61) ~[?:?]
	at org.cyberpwn.commune.CommuneController.<init>(CommuneController.java:208) ~[?:?]
	at org.cyberpwn.commune.Commune.enable(Commune.java:33) ~[?:?]
	at org.phantomapi.construct.ControllablePlugin.onEnable(ControllablePlugin.java:82) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: de.dustplanet.util.SilkUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	... 15 more
```

**Comment by SwiftSwamp** [comment]
Ahh, Commune is enabling before SilkSpawners... thrashing the server works but SS seems to be required on every server.

**Comment by cyberpwnn** [comment]
https://github.com/cyberpwnn/Commune/commit/529757bdbaaadca7b3628966bd9b4ca02b53634c
