### ISSUE TITLE
Phantom D5 Bug

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#680]
```
[13:36:47] [Server thread/WARN]: [Phantom] Task #166194 for Phantom vD5 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.block.CraftBlockState cannot be cast to org.bukkit.block.CreatureSpawner
	at org.phantomapi.spawner.PhantomSpawner.setType(PhantomSpawner.java:18) ~[?:?]
	at org.cyberpwn.commune.CombatController$1.run(CombatController.java:229) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
```

**Comment by cyberpwnn** [comment]
https://github.com/PhantomAPI/Phantom/commit/f4d93b7f398841f1b988bbe0eae7e77bd696f1f8
